version: 2

sources:
  - name: biathlon_raw
    database: biathlon_raw
    tables:
      - name: results
      - name: analytics_results
      - name: competitions
      - name: events
      - name: results_og
      - name: competitions_og
      - name: events_og
